version: "3.8"

services:
  kafka-consumer:
    container_name: kafka-consumer
    build: .
    ports:
      - "5999:5999"
    env_file:
      - .env      # ✅ 네가 말한 실제 경로 반영!
    restart: unless-stopped
