spring:
  config:
    import: optional:file:.env

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/fullter
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
