name: CI/CD HTTP Deploy (Gradle)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build (Gradle)
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          OWNER_LC=$(echo "${{ env.OWNER }}" | tr '[:upper:]' '[:lower:]')
          docker build --no-cache -t ghcr.io/${OWNER_LC}/consumer:${GITHUB_SHA} .

      - name: Push Docker image
        run: |
          OWNER_LC=$(echo "${{ env.OWNER }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${OWNER_LC}/consumer:${GITHUB_SHA}

      - name: Tag and push latest
        run: |
          OWNER_LC=$(echo "${{ env.OWNER }}" | tr '[:upper:]' '[:lower:]')
          docker tag ghcr.io/${OWNER_LC}/consumer:${GITHUB_SHA} ghcr.io/${OWNER_LC}/consumer:latest
          docker push ghcr.io/${OWNER_LC}/consumer:latest

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Open port 22 temporarily
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp --port 22 --cidr 0.0.0.0/0 || true

      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            OWNER_LC=$(echo "${{ env.OWNER }}" | tr '[:upper:]' '[:lower:]')
            IMAGE="ghcr.io/${OWNER_LC}/consumer:${{ github.sha }}"

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker rm -f kafka-consumer || true
            docker pull "$IMAGE"
            docker run -d --name kafka-consumer --restart=always \
              --env-file /home/ubuntu/kafka-consumer/.env \
              "$IMAGE"

            docker network connect kafka-docker_kafka-net kafka-consumer || true

      - name: Close port 22
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp --port 22 --cidr 0.0.0.0/0 || true
